PricingSettingDecorator:
    type: object
    decorator: true
    config:
        description: "Represents setting of pricing"
        fields:
            defaultCurrencyCode:
                type: "String!"
                description: "Code of the default currency used on the current domain"
            minimumFractionDigits:
                type: "Int!"
                description: "Minimum number of decimal places for the price on the current domain"
            freeTransportAndPaymentPriceWithVatLimit:
                type: "Money"
                description: "Price limit with VAT for free transport and payment (NULL means free transport and payment is not active)"
